### ISSUE TITLE
Addon burns preview into original image

### ISSUE THREAD

**Issue by schroef** [akej74/hdri-sun-aligner#6]
v0.3.1.2
bl2.83

I was testing this issue and had some issues with a file getting the proper position. I made a preview file and then started it from scratch to see if it works then. Loading the same HDR image, i noticed the preview circle then was saved into the original image.

I used the pack function in the other file and opened and closed it couple times. Not sure when in this process the original image was saved with that preview circle

See attached screengrab
![Screen Shot 2022-01-31 at 11 10 56](https://user-images.githubusercontent.com/6923008/151818857-1f43c079-0db4-445f-8e70-623649a35ca0.png)

**Comment by akej74** [comment]
Thanks for the report, the addon should not modify the original HDRI (it's making a temporary copy with another name before adding the sun position indicator). Can you reproduce this problem? If so, please provide a step by step guide (starting from a new scene in Blender) on how to reproduce the issue.

**Comment by akej74** [comment]
Thanks for the feedback, closing this.
